version: "3.3"
services:
  tomcat:
    image: tomcat:9
    ports:
      - "8080:8080"
      - "8000:8000" # used for debug
      - "9010:9010" # used for debug
    environment:
      # start tomcat catalina on debug mode 
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
    # this is the default command:
    # command: bash -c "catalina.sh run"
    command: bash -c "cp /tmp/lib/additional_catalina_params.txt /tmp/x && cat /usr/local/tomcat/bin/catalina.sh >> /tmp/x && cat /tmp/x > /usr/local/tomcat/bin/catalina.sh && rm /tmp/x && catalina.sh run"
    volumes:
      - ./target/image-search-api:/usr/local/tomcat/webapps/ROOT
      # uncomment this to access tomcat logs without having to enter the docker container:
      # - ./logs:/usr/local/tomcat/logs
      - ./lib:/tmp/lib
